//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public int Amount { get; set; }
        public int OrderNumber { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
        public int IdPaymentMethod { get; set; }
        public string BillingAddress { get; set; }
        public string DateActiveOrders { get; set; }
        public string Date { get; set; }
    }
}
