//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> PictureId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberStringId { get; set; }
        public decimal Price { get; set; }
        public int NumberProduct { get; set; }
        public System.DateTime DateManufacture { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public int SubcategoriesId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Country Country { get; set; }
        public virtual NumberString NumberString { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
}
